INSERT INTO users (
        user_name,
        user_middle_name,
        user_last_name,
        email,
        password,
        assignedPhone,
        rfc,
        curp,
        city,
        state,
        country,
        position_id,
        department_id,
        role,
        created_at,
        created_by,
        modified_by,
        modified_at,
        username
    )
VALUES (
        'Luis',
        '',
        'Moreno',
        'luis.moreno@garle.com.mx',
        '$2a$12$qyVoKzsB6AkN6mlypZLoweT5Y3GvhgutDNZySQmgExoJbqMdWXoCG',
        12345678910,
        'ABCD202020A12',
        'ESRDTFYGUHJK9865312',
        "Juarez",
        "Chihuahua",
        "Mexico",
        "Jefe",
        "Jefe",
        '1',
        '2022-08-30 19:47:16',
        '1',
        '1',
        '2022-08-30 19:47:16',
        'luis.moreno'
    );